# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 920)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* main */\n"
"QMainWindow {\n"
"    background-color: rgb(79, 90, 112);\n"
"}\n"
"/* menubar */\n"
"QMenuBar {    \n"
"    font: 63 9pt \"Segoe UI Variable Text Semibold\";\n"
"    color: rgb(138, 138, 138);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(207, 209, 207, 255), stop:1 rgba(230, 229, 230, 255));\n"
"}\n"
"QMenuBar::item:selected {\n"
"      background-color: rgb(161, 186, 230);\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item{    \n"
"    font: 8pt \"Segoe UI\";\n"
"}\n"
"QMenu::item:selected {\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: rgb(161, 186, 230);\n"
"    border-bottom-color: transparent;\n"
"    border-left-width: 2px;\n"
"    color: #000000;\n"
"    padding-left:15px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"QMenu::item {\n"
"    font: 8pt \"Segoe UI\";\n"
"    border-style: solid;\n"
"    border-top-color: transparent;\n"
"    border-right-color: transparent;\n"
"    border-left-color: transparent;\n"
"    border-bottom-color: transparent;\n"
"    border-bottom-width: 1px;\n"
"    color: #000000;\n"
"    padding-left:10px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:7px;\n"
"}\n"
"/* push button */\n"
"QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(82, 94, 117);\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-radius: 15px;\n"
"    border-color: rgb(82, 94, 117);\n"
"    border-width: 2px;\n"
"    /*background-color: rgb(185, 222, 255);*/\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-radius: 15px;\n"
"    border-color: rgb(138, 173, 204);\n"
"    border-width: 2px;\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"/* slider */\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(82, 94, 117);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(79, 90, 112);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"/* LCD */\n"
"QLCDNumber {\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    border-style:solid;\n"
"    border-radius:7px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(79, 90, 112);\n"
"    /*color: rgb(140, 162, 202);*/\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"/* checkbox */\n"
"QCheckBox:hover {\n"
"    border-radius:2px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:2px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    height: 11px;\n"
"    width: 11px;\n"
"    border-style:solid;\n"
"    border-radius: 2px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(79, 90, 112);\n"
"    color: #000000;\n"
"    background-color: rgb(161, 186, 230);\n"
"\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 11px;\n"
"    width: 11px;\n"
"    border-style:solid;\n"
"    border-radius: 2px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(79, 90, 112);\n"
"    color: #000000;\n"
"}\n"
"/* combobox */\n"
"QComboBox{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(82, 94, 117);\n"
"    border-radius: 2px;\n"
"}/*\n"
"QListView::item {\n"
"    border-bottom: 5px solid white; margin:3px;\n"
"}\n"
"QListView::item:selected {\n"
"    border-bottom: 5px solid black; margin:3px;\n"
"    color: black;\n"
"}*/\n"
"QComboBox::item{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(82, 94, 117);\n"
"    border-radius: 2px;\n"
"}\n"
"/* tab */\n"
"QTabWidget {\n"
"    border-radius: 6px;\n"
"    color:rgb(0,0,0);\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(223,223,223);\n"
"        background-color:rgb(226,226,226);\n"
"        border-style: solid;\n"
"        border-width: 2px;\n"
"        border-top-right-radius: 6px;\n"
"        border-bottom-right-radius: 6px;\n"
"        border-bottom-left-radius: 6px;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-style: solid;\n"
"    border-left-width:1px;\n"
"    border-right-width:0px;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color: rgb(229, 229, 229);\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-left-radius: 4px;\n"
"    /*border-bottom-left-radius: 4px;*/\n"
"    color: #000000;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color:  rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-style: solid;\n"
"    border-width:1px;\n"
"    border-top-color: rgb(209,209,209);\n"
"    border-left-color:rgb(229, 229, 229);\n"
"    border-right-color: rgb(229, 229, 229);\n"
"    border-bottom-color: rgb(229,229,229);\n"
"    border-top-right-radius: 4px;\n"
"    /*border-bottom-right-radius: 4px;*/\n"
"    color: #000000;\n"
"    padding: 4px;\n"
"    margin-left:0px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:2px;\n"
"    border-right-color: rgb(82, 94, 117);\n"
"    border-top-color: rgb(82, 94, 117);\n"
"    border-left-color: rgb(82, 94, 117);\n"
"    border-bottom-color: rgb(82, 94, 117);\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: rgb(161, 186, 230);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:first:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-right-width:2px;\n"
"    border-right-color: rgb(82, 94, 117);\n"
"    border-top-color: rgb(82, 94, 117);\n"
"    border-left-color: rgb(82, 94, 117);\n"
"    border-bottom-color: rgb(82, 94, 117);\n"
"    border-left-width: 1px;\n"
"    color: #ffffff;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: rgb(161, 186, 230);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setHorizontalSpacing(10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 0, 2, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setEnabled(False)
        self.toolButton.setAutoFillBackground(False)
        self.toolButton.setStyleSheet("    background-color: rgb(79, 90, 112);\n"
"")
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons/signal processing studio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(40, 40))
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_13.addWidget(self.toolButton, 0, 1, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 800))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_composer = QtWidgets.QWidget()
        self.tab_composer.setObjectName("tab_composer")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.tab_composer)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_result_signal = QtWidgets.QGroupBox(self.tab_composer)
        self.groupBox_result_signal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.groupBox_result_signal.setFont(font)
        self.groupBox_result_signal.setAutoFillBackground(True)
        self.groupBox_result_signal.setObjectName("groupBox_result_signal")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_result_signal)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setVerticalSpacing(35)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plotwidget_result = PlotWidget(self.groupBox_result_signal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotwidget_result.sizePolicy().hasHeightForWidth())
        self.plotwidget_result.setSizePolicy(sizePolicy)
        self.plotwidget_result.setMinimumSize(QtCore.QSize(1100, 300))
        self.plotwidget_result.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.plotwidget_result.setFont(font)
        self.plotwidget_result.setAutoFillBackground(True)
        self.plotwidget_result.setObjectName("plotwidget_result")
        self.gridLayout_6.addWidget(self.plotwidget_result, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_result_signal)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_clear.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icons/clear2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear.setIcon(icon1)
        self.pushButton_clear.setIconSize(QtCore.QSize(15, 20))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_5.addWidget(self.pushButton_clear, 0, 1, 1, 1)
        self.pushButton_next = QtWidgets.QPushButton(self.groupBox_result_signal)
        self.pushButton_next.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_next.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.pushButton_next.setFont(font)
        self.pushButton_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_next.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_next.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icons/next2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon2)
        self.pushButton_next.setFlat(False)
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout_5.addWidget(self.pushButton_next, 0, 2, 1, 1)
        self.pushButton_export = QtWidgets.QPushButton(self.groupBox_result_signal)
        self.pushButton_export.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_export.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_export.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/icons/export2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_export.setIcon(icon3)
        self.pushButton_export.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout_5.addWidget(self.pushButton_export, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_6.setRowStretch(0, 3)
        self.gridLayout_6.setRowStretch(1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_result_signal, 0, 1, 1, 1)
        self.groupBox_signal_mixer = QtWidgets.QGroupBox(self.tab_composer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_signal_mixer.sizePolicy().hasHeightForWidth())
        self.groupBox_signal_mixer.setSizePolicy(sizePolicy)
        self.groupBox_signal_mixer.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox_signal_mixer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.groupBox_signal_mixer.setFont(font)
        self.groupBox_signal_mixer.setAutoFillBackground(True)
        self.groupBox_signal_mixer.setStyleSheet("")
        self.groupBox_signal_mixer.setObjectName("groupBox_signal_mixer")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_signal_mixer)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.plotwidget_mixer = PlotWidget(self.groupBox_signal_mixer)
        self.plotwidget_mixer.setMinimumSize(QtCore.QSize(0, 300))
        self.plotwidget_mixer.setMaximumSize(QtCore.QSize(16777215, 550))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.plotwidget_mixer.setFont(font)
        self.plotwidget_mixer.setAutoFillBackground(True)
        self.plotwidget_mixer.setObjectName("plotwidget_mixer")
        self.gridLayout_15.addWidget(self.plotwidget_mixer, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(7)
        self.gridLayout_8.setVerticalSpacing(35)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setHorizontalSpacing(20)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalSlider_freq = QtWidgets.QSlider(self.groupBox_signal_mixer)
        self.horizontalSlider_freq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalSlider_freq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_freq.setAutoFillBackground(True)
        self.horizontalSlider_freq.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_freq.setObjectName("horizontalSlider_freq")
        self.gridLayout_9.addWidget(self.horizontalSlider_freq, 0, 1, 1, 1)
        self.lcdNumber_freq = QtWidgets.QLCDNumber(self.groupBox_signal_mixer)
        self.lcdNumber_freq.setMinimumSize(QtCore.QSize(0, 25))
        self.lcdNumber_freq.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lcdNumber_freq.setStyleSheet("\n"
"background-color: rgb(161, 186, 230);\n"
"")
        self.lcdNumber_freq.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_freq.setSmallDecimalPoint(False)
        self.lcdNumber_freq.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_freq.setObjectName("lcdNumber_freq")
        self.gridLayout_9.addWidget(self.lcdNumber_freq, 0, 2, 1, 1)
        self.label_freq = QtWidgets.QLabel(self.groupBox_signal_mixer)
        self.label_freq.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.label_freq.setFont(font)
        self.label_freq.setObjectName("label_freq")
        self.gridLayout_9.addWidget(self.label_freq, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setHorizontalSpacing(20)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_amplitude = QtWidgets.QLabel(self.groupBox_signal_mixer)
        self.label_amplitude.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.label_amplitude.setFont(font)
        self.label_amplitude.setObjectName("label_amplitude")
        self.gridLayout_10.addWidget(self.label_amplitude, 0, 0, 1, 1)
        self.lcdNumber_amplitude = QtWidgets.QLCDNumber(self.groupBox_signal_mixer)
        self.lcdNumber_amplitude.setMinimumSize(QtCore.QSize(0, 25))
        self.lcdNumber_amplitude.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lcdNumber_amplitude.setAutoFillBackground(False)
        self.lcdNumber_amplitude.setStyleSheet("background-color: rgb(161, 186, 230);\n"
"color: rgb(0, 0, 0);")
        self.lcdNumber_amplitude.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_amplitude.setLineWidth(1)
        self.lcdNumber_amplitude.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_amplitude.setObjectName("lcdNumber_amplitude")
        self.gridLayout_10.addWidget(self.lcdNumber_amplitude, 0, 2, 1, 1)
        self.horizontalSlider_amplitude = QtWidgets.QSlider(self.groupBox_signal_mixer)
        self.horizontalSlider_amplitude.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalSlider_amplitude.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_amplitude.setAutoFillBackground(True)
        self.horizontalSlider_amplitude.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_amplitude.setObjectName("horizontalSlider_amplitude")
        self.gridLayout_10.addWidget(self.horizontalSlider_amplitude, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 1, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setHorizontalSpacing(20)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalSlider_phase = QtWidgets.QSlider(self.groupBox_signal_mixer)
        self.horizontalSlider_phase.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalSlider_phase.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_phase.setAutoFillBackground(True)
        self.horizontalSlider_phase.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_phase.setObjectName("horizontalSlider_phase")
        self.gridLayout_11.addWidget(self.horizontalSlider_phase, 0, 1, 1, 1)
        self.lcdNumber_phase = QtWidgets.QLCDNumber(self.groupBox_signal_mixer)
        self.lcdNumber_phase.setMinimumSize(QtCore.QSize(0, 25))
        self.lcdNumber_phase.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lcdNumber_phase.setStyleSheet("background-color: rgb(161, 186, 230);\n"
"")
        self.lcdNumber_phase.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_phase.setSmallDecimalPoint(False)
        self.lcdNumber_phase.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_phase.setObjectName("lcdNumber_phase")
        self.gridLayout_11.addWidget(self.lcdNumber_phase, 0, 2, 1, 1)
        self.label_phase = QtWidgets.QLabel(self.groupBox_signal_mixer)
        self.label_phase.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.label_phase.setFont(font)
        self.label_phase.setObjectName("label_phase")
        self.gridLayout_11.addWidget(self.label_phase, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.groupBox_signal_mixer)
        self.pushButton_add.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_add.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_add.setAutoFillBackground(False)
        self.pushButton_add.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_add.setIcon(icon4)
        self.pushButton_add.setAutoDefault(False)
        self.pushButton_add.setDefault(False)
        self.pushButton_add.setFlat(False)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout_2.addWidget(self.pushButton_add, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(5)
        self.gridLayout_4.setVerticalSpacing(7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_signals = QtWidgets.QComboBox(self.groupBox_signal_mixer)
        self.comboBox_signals.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_signals.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.comboBox_signals.setFont(font)
        self.comboBox_signals.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_signals.setAutoFillBackground(False)
        self.comboBox_signals.setObjectName("comboBox_signals")
        self.gridLayout_4.addWidget(self.comboBox_signals, 0, 0, 1, 1)
        self.pushButton_delete = QtWidgets.QPushButton(self.groupBox_signal_mixer)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_delete.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_delete.setAutoFillBackground(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_delete.setIcon(icon5)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.gridLayout_4.addWidget(self.pushButton_delete, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_signal_mixer, 0, 0, 1, 1)
        self.gridLayout_12.setColumnStretch(0, 2)
        self.gridLayout_12.setColumnStretch(1, 3)
        self.gridLayout_28.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_composer, "")
        self.tab_sampler = QtWidgets.QWidget()
        self.tab_sampler.setObjectName("tab_sampler")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tab_sampler)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.groupBox_original_signal = QtWidgets.QGroupBox(self.tab_sampler)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.groupBox_original_signal.setFont(font)
        self.groupBox_original_signal.setAutoFillBackground(True)
        self.groupBox_original_signal.setObjectName("groupBox_original_signal")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_original_signal)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.plotwidget_original = PlotWidget(self.groupBox_original_signal)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.plotwidget_original.setFont(font)
        self.plotwidget_original.setAutoFillBackground(True)
        self.plotwidget_original.setObjectName("plotwidget_original")
        self.gridLayout_20.addWidget(self.plotwidget_original, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_original_signal, 0, 0, 1, 1)
        self.groupBox_error = QtWidgets.QGroupBox(self.tab_sampler)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.groupBox_error.setFont(font)
        self.groupBox_error.setAutoFillBackground(True)
        self.groupBox_error.setObjectName("groupBox_error")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_error)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.plotwidget_error = PlotWidget(self.groupBox_error)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.plotwidget_error.setFont(font)
        self.plotwidget_error.setAutoFillBackground(True)
        self.plotwidget_error.setObjectName("plotwidget_error")
        self.gridLayout_18.addWidget(self.plotwidget_error, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_error, 2, 0, 1, 1)
        self.groupBox_reconstructed_sig = QtWidgets.QGroupBox(self.tab_sampler)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.groupBox_reconstructed_sig.setFont(font)
        self.groupBox_reconstructed_sig.setAutoFillBackground(True)
        self.groupBox_reconstructed_sig.setObjectName("groupBox_reconstructed_sig")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_reconstructed_sig)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.plotwidget_reconstructed = PlotWidget(self.groupBox_reconstructed_sig)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.plotwidget_reconstructed.setFont(font)
        self.plotwidget_reconstructed.setAutoFillBackground(True)
        self.plotwidget_reconstructed.setObjectName("plotwidget_reconstructed")
        self.gridLayout_19.addWidget(self.plotwidget_reconstructed, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_reconstructed_sig, 1, 0, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setHorizontalSpacing(15)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.checkBox_noise = QtWidgets.QCheckBox(self.tab_sampler)
        self.checkBox_noise.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.checkBox_noise.setFont(font)
        self.checkBox_noise.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_noise.setAutoFillBackground(False)
        self.checkBox_noise.setObjectName("checkBox_noise")
        self.gridLayout_24.addWidget(self.checkBox_noise, 0, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setHorizontalSpacing(10)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_SNR = QtWidgets.QLabel(self.tab_sampler)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.label_SNR.setFont(font)
        self.label_SNR.setAutoFillBackground(False)
        self.label_SNR.setObjectName("label_SNR")
        self.gridLayout_23.addWidget(self.label_SNR, 1, 0, 1, 1)
        self.horizontalSlider_SNR = QtWidgets.QSlider(self.tab_sampler)
        self.horizontalSlider_SNR.setMinimumSize(QtCore.QSize(370, 35))
        self.horizontalSlider_SNR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_SNR.setAutoFillBackground(False)
        self.horizontalSlider_SNR.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_SNR.setObjectName("horizontalSlider_SNR")
        self.gridLayout_23.addWidget(self.horizontalSlider_SNR, 1, 1, 1, 1)
        self.lcdNumber_SNR = QtWidgets.QLCDNumber(self.tab_sampler)
        self.lcdNumber_SNR.setMinimumSize(QtCore.QSize(0, 25))
        self.lcdNumber_SNR.setStyleSheet("background-color: rgb(161, 186, 230);\n"
"\n"
"")
        self.lcdNumber_SNR.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_SNR.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_SNR.setObjectName("lcdNumber_SNR")
        self.gridLayout_23.addWidget(self.lcdNumber_SNR, 1, 2, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_23, 1, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_24, 0, 0, 1, 1)
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setHorizontalSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.radioButton_normalized = QtWidgets.QRadioButton(self.tab_sampler)
        self.radioButton_normalized.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.radioButton_normalized.setFont(font)
        self.radioButton_normalized.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_normalized.setAutoFillBackground(False)
        self.radioButton_normalized.setAutoExclusive(True)
        self.radioButton_normalized.setObjectName("radioButton_normalized")
        self.gridLayout_21.addWidget(self.radioButton_normalized, 0, 0, 1, 1)
        self.radioButton_actual = QtWidgets.QRadioButton(self.tab_sampler)
        self.radioButton_actual.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.radioButton_actual.setFont(font)
        self.radioButton_actual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_actual.setAutoFillBackground(False)
        self.radioButton_actual.setObjectName("radioButton_actual")
        self.gridLayout_21.addWidget(self.radioButton_actual, 0, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setHorizontalSpacing(10)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalSlider_fs = QtWidgets.QSlider(self.tab_sampler)
        self.horizontalSlider_fs.setMinimumSize(QtCore.QSize(370, 35))
        self.horizontalSlider_fs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_fs.setAutoFillBackground(False)
        self.horizontalSlider_fs.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_fs.setObjectName("horizontalSlider_fs")
        self.gridLayout_22.addWidget(self.horizontalSlider_fs, 0, 1, 1, 1)
        self.label_fs = QtWidgets.QLabel(self.tab_sampler)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.label_fs.setFont(font)
        self.label_fs.setObjectName("label_fs")
        self.gridLayout_22.addWidget(self.label_fs, 0, 0, 1, 1)
        self.lcdNumber_fs = QtWidgets.QLCDNumber(self.tab_sampler)
        self.lcdNumber_fs.setMinimumSize(QtCore.QSize(0, 25))
        self.lcdNumber_fs.setStyleSheet("background-color: rgb(161, 186, 230);\n"
"")
        self.lcdNumber_fs.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_fs.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_fs.setObjectName("lcdNumber_fs")
        self.gridLayout_22.addWidget(self.lcdNumber_fs, 0, 2, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_22, 1, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_26, 0, 1, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.pushButton_clear_all = QtWidgets.QPushButton(self.tab_sampler)
        self.pushButton_clear_all.setMinimumSize(QtCore.QSize(80, 36))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 94, 117))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton_clear_all.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.pushButton_clear_all.setFont(font)
        self.pushButton_clear_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear_all.setAutoFillBackground(False)
        self.pushButton_clear_all.setIcon(icon1)
        self.pushButton_clear_all.setIconSize(QtCore.QSize(15, 20))
        self.pushButton_clear_all.setObjectName("pushButton_clear_all")
        self.gridLayout_25.addWidget(self.pushButton_clear_all, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_25, 0, 2, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        self.gridLayout_29.setRowStretch(0, 3)
        self.gridLayout_30.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_sampler, "")
        self.gridLayout_14.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.triggered.connect(QtWidgets.QApplication.instance().quit)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon6)
        self.actionClose.setObjectName("actionClose")
        self.actionComposer = QtWidgets.QAction(MainWindow)
        self.actionComposer.setObjectName("actionComposer")
        self.actionSampler = QtWidgets.QAction(MainWindow)
        self.actionSampler.setObjectName("actionSampler")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon7)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.horizontalSlider_freq.valueChanged['int'].connect(self.lcdNumber_freq.display) # type: ignore
        self.horizontalSlider_amplitude.valueChanged['int'].connect(self.lcdNumber_amplitude.display) # type: ignore
        self.horizontalSlider_phase.valueChanged['int'].connect(self.lcdNumber_phase.display) # type: ignore
        self.horizontalSlider_SNR.valueChanged['int'].connect(self.lcdNumber_SNR.display) # type: ignore
        self.horizontalSlider_fs.valueChanged['int'].connect(self.lcdNumber_fs.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#     def update_lcd_display(self, value):
#         # Subtract 1 from the slider's value
#         modified_value = value - 1
#         # Update the LCD display with the modified value
#         self.lcdNumber_fs.display(modified_value)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Sampling Studio"))
        self.tabWidget.setToolTip(_translate("MainWindow", "Composer tab"))
        self.groupBox_result_signal.setTitle(_translate("MainWindow", "Result Signal"))
        self.pushButton_clear.setToolTip(_translate("MainWindow", "Clear the result signal"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.pushButton_clear.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.pushButton_next.setToolTip(_translate("MainWindow", "Go to the sampler "))
        self.pushButton_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_next.setShortcut(_translate("MainWindow", "Right"))
        self.pushButton_export.setToolTip(_translate("MainWindow", "Export the result signal to a csv file"))
        self.pushButton_export.setText(_translate("MainWindow", "Export"))
        self.pushButton_export.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.groupBox_signal_mixer.setTitle(_translate("MainWindow", "Signal Mixer"))
        self.horizontalSlider_freq.setToolTip(_translate("MainWindow", "Frequency"))
        self.lcdNumber_freq.setToolTip(_translate("MainWindow", "Frequency"))
        self.label_freq.setToolTip(_translate("MainWindow", "Frequency"))
        self.label_freq.setText(_translate("MainWindow", "Frequency"))
        self.label_amplitude.setToolTip(_translate("MainWindow", "Amplitude"))
        self.label_amplitude.setText(_translate("MainWindow", "Amplitude"))
        self.lcdNumber_amplitude.setToolTip(_translate("MainWindow", "Amplitude"))
        self.horizontalSlider_amplitude.setToolTip(_translate("MainWindow", "Amplitude"))
        self.horizontalSlider_phase.setToolTip(_translate("MainWindow", "Phase"))
        self.lcdNumber_phase.setToolTip(_translate("MainWindow", "Phase"))
        self.label_phase.setToolTip(_translate("MainWindow", "Phase"))
        self.label_phase.setText(_translate("MainWindow", "Phase"))
        self.pushButton_add.setToolTip(_translate("MainWindow", "Add this signal to the result signal"))
        self.pushButton_add.setText(_translate("MainWindow", "Add"))
        self.pushButton_add.setShortcut(_translate("MainWindow", "Return"))
        self.comboBox_signals.setToolTip(_translate("MainWindow", "Choose a signal"))
        self.pushButton_delete.setToolTip(_translate("MainWindow", "Delete this signal"))
        self.pushButton_delete.setText(_translate("MainWindow", "Delete"))
        self.pushButton_delete.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_composer), _translate("MainWindow", "Composer"))
        self.groupBox_original_signal.setTitle(_translate("MainWindow", "Original Signal"))
        self.groupBox_error.setTitle(_translate("MainWindow", "Error"))
        self.groupBox_reconstructed_sig.setTitle(_translate("MainWindow", "Reconstructed Signal"))
        self.checkBox_noise.setToolTip(_translate("MainWindow", "Noise"))
        self.checkBox_noise.setText(_translate("MainWindow", "Noise"))
        self.checkBox_noise.setShortcut(_translate("MainWindow", "Shift+N"))
        self.label_SNR.setToolTip(_translate("MainWindow", "Signal-to-Noise Ratio"))
        self.label_SNR.setText(_translate("MainWindow", "SNR"))
        self.horizontalSlider_SNR.setToolTip(_translate("MainWindow", "Signal-to-Noise Ratio"))
        self.lcdNumber_SNR.setToolTip(_translate("MainWindow", "Signal-to-Noise Ratio"))
        self.radioButton_normalized.setToolTip(_translate("MainWindow", "Show the normalived signal"))
        self.radioButton_normalized.setText(_translate("MainWindow", "Normalized signal"))
        self.radioButton_actual.setToolTip(_translate("MainWindow", "Show the actual signal"))
        self.radioButton_actual.setText(_translate("MainWindow", "Actual signal"))
        self.horizontalSlider_fs.setToolTip(_translate("MainWindow", "Sampling Frequency"))
        self.label_fs.setToolTip(_translate("MainWindow", "Sampling Frequency"))
        self.label_fs.setText(_translate("MainWindow", " fs"))
        self.lcdNumber_fs.setToolTip(_translate("MainWindow", "Sampling Frequency"))
        self.pushButton_clear_all.setToolTip(_translate("MainWindow", "Clear all"))
        self.pushButton_clear_all.setText(_translate("MainWindow", "Clear All"))
        self.pushButton_clear_all.setShortcut(_translate("MainWindow", "Ctrl+K"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sampler), _translate("MainWindow", "Sampler"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionComposer.setText(_translate("MainWindow", "Composer"))
        self.actionSampler.setText(_translate("MainWindow", "Sampler"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
